#!/usr/bin/env python3
"""
ARM-to-RV64I Cross Translator
==============================

Translates ARMv4T (arm7tdmi) assembly into RV64I machine code.

This tool reads ARM assembly files (as generated by `arm-none-eabi-gcc -S`)
and produces:
  1. Equivalent RV64I assembly (.S file)
  2. RV64I machine code hex (.hex file)
  3. Verilog memory initialization statements (.v file)

Supported ARM instructions (subset for bubble sort and similar programs):
  - Data processing: mov, add, sub, and, orr, eor, lsl, lsr, asr, cmp, rsb, mvn
  - Multiply: mul
  - Load/Store: ldr, str, ldrb, strb, ldrh, strh
  - Multi load/store: ldmia, stmia, ldm, stm (expanded to individual ld/sd)
  - Branch: b, bge, bgt, blt, ble, beq, bne, bx
  - Stack: push, pop
  - Immediate shifts: lsl/lsr/asr as part of data processing

Register mapping (ARM -> RV64I):
  ARM r0-r12  -> RV64I x10-x22 (a0-a2, a3-a7, s2-s6)
  ARM sp (r13) -> RV64I x2 (sp)
  ARM lr (r14) -> RV64I x1 (ra)
  ARM pc (r15) -> (not directly mapped)
  ARM fp (r11) -> RV64I x8 (s0/fp)
  ARM ip (r12) -> RV64I x22 (s6, scratch)

Usage:
  python3 arm2rv64i.py input.s [-o output_prefix] [--base-addr 0x000]
  python3 arm2rv64i.py sort.s -o sort --verilog --hex

生成所有格式（.S汇编 + .hex + .v Verilog初始化）
python3 arm2rv64i.py sort.s -o sort --all

指定线程起始地址（用于多线程）
python3 arm2rv64i.py prog1.s --base-addr 0x200 -o thread1

只生成Verilog初始化
python3 arm2rv64i.py sort.s --verilog

Author: Generated for EE533 Lab 6
"""

import sys
import re
import argparse
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional


# =============================================================================
# RV64I Encoding Functions
# =============================================================================

def encode_r(funct7, rs2, rs1, funct3, rd, opcode=0x33):
    """R-type: funct7[31:25] rs2[24:20] rs1[19:15] funct3[14:12] rd[11:7] opcode[6:0]"""
    return ((funct7 & 0x7F) << 25) | ((rs2 & 0x1F) << 20) | ((rs1 & 0x1F) << 15) | \
           ((funct3 & 0x7) << 12) | ((rd & 0x1F) << 7) | (opcode & 0x7F)

def encode_i(imm12, rs1, funct3, rd, opcode):
    """I-type: imm[31:20] rs1[19:15] funct3[14:12] rd[11:7] opcode[6:0]"""
    return ((imm12 & 0xFFF) << 20) | ((rs1 & 0x1F) << 15) | \
           ((funct3 & 0x7) << 12) | ((rd & 0x1F) << 7) | (opcode & 0x7F)

def encode_s(imm12, rs2, rs1, funct3, opcode=0x23):
    """S-type: imm[11:5][31:25] rs2[24:20] rs1[19:15] funct3[14:12] imm[4:0][11:7] opcode[6:0]"""
    imm = imm12 & 0xFFF
    return (((imm >> 5) & 0x7F) << 25) | ((rs2 & 0x1F) << 20) | ((rs1 & 0x1F) << 15) | \
           ((funct3 & 0x7) << 12) | ((imm & 0x1F) << 7) | (opcode & 0x7F)

def encode_b(offset, rs1, rs2, funct3, opcode=0x63):
    """B-type: imm[12|10:5][31:25] rs2[24:20] rs1[19:15] funct3[14:12] imm[4:1|11][11:7] opcode[6:0]"""
    off = offset & 0x1FFFFE  # 13-bit signed, bit 0 always 0
    if offset < 0:
        off = offset & 0x1FFF
    imm12 = (offset >> 12) & 1
    imm10_5 = (offset >> 5) & 0x3F
    imm4_1 = (offset >> 1) & 0xF
    imm11 = (offset >> 11) & 1
    return (imm12 << 31) | (imm10_5 << 25) | ((rs2 & 0x1F) << 20) | ((rs1 & 0x1F) << 15) | \
           ((funct3 & 0x7) << 12) | (imm4_1 << 8) | (imm11 << 7) | (opcode & 0x7F)

def encode_u(imm20, rd, opcode):
    """U-type: imm[31:12] rd[11:7] opcode[6:0]"""
    return ((imm20 & 0xFFFFF) << 12) | ((rd & 0x1F) << 7) | (opcode & 0x7F)

def encode_j(offset, rd, opcode=0x6F):
    """J-type (JAL): imm[20|10:1|11|19:12][31:12] rd[11:7] opcode[6:0]"""
    imm20 = (offset >> 20) & 1
    imm10_1 = (offset >> 1) & 0x3FF
    imm11 = (offset >> 11) & 1
    imm19_12 = (offset >> 12) & 0xFF
    return (imm20 << 31) | (imm10_1 << 21) | (imm11 << 20) | (imm19_12 << 12) | \
           ((rd & 0x1F) << 7) | (opcode & 0x7F)


# Helper to generate RV64I instructions by name
def rv_add(rd, rs1, rs2):    return encode_r(0x00, rs2, rs1, 0x0, rd, 0x33)
def rv_sub(rd, rs1, rs2):    return encode_r(0x20, rs2, rs1, 0x0, rd, 0x33)
def rv_and(rd, rs1, rs2):    return encode_r(0x00, rs2, rs1, 0x7, rd, 0x33)
def rv_or(rd, rs1, rs2):     return encode_r(0x00, rs2, rs1, 0x6, rd, 0x33)
def rv_xor(rd, rs1, rs2):    return encode_r(0x00, rs2, rs1, 0x4, rd, 0x33)
def rv_sll(rd, rs1, rs2):    return encode_r(0x00, rs2, rs1, 0x1, rd, 0x33)
def rv_srl(rd, rs1, rs2):    return encode_r(0x00, rs2, rs1, 0x5, rd, 0x33)
def rv_sra(rd, rs1, rs2):    return encode_r(0x20, rs2, rs1, 0x5, rd, 0x33)
def rv_slt(rd, rs1, rs2):    return encode_r(0x00, rs2, rs1, 0x2, rd, 0x33)
def rv_sltu(rd, rs1, rs2):   return encode_r(0x00, rs2, rs1, 0x3, rd, 0x33)

def rv_addi(rd, rs1, imm):   return encode_i(imm & 0xFFF, rs1, 0x0, rd, 0x13)
def rv_andi(rd, rs1, imm):   return encode_i(imm & 0xFFF, rs1, 0x7, rd, 0x13)
def rv_ori(rd, rs1, imm):    return encode_i(imm & 0xFFF, rs1, 0x6, rd, 0x13)
def rv_xori(rd, rs1, imm):   return encode_i(imm & 0xFFF, rs1, 0x4, rd, 0x13)
def rv_slti(rd, rs1, imm):   return encode_i(imm & 0xFFF, rs1, 0x2, rd, 0x13)
def rv_sltiu(rd, rs1, imm):  return encode_i(imm & 0xFFF, rs1, 0x3, rd, 0x13)
def rv_slli(rd, rs1, shamt): return encode_i(shamt & 0x3F, rs1, 0x1, rd, 0x13)
def rv_srli(rd, rs1, shamt): return encode_i(shamt & 0x3F, rs1, 0x5, rd, 0x13)
def rv_srai(rd, rs1, shamt): return encode_i((0x400 | (shamt & 0x3F)), rs1, 0x5, rd, 0x13)

def rv_lb(rd, rs1, imm):     return encode_i(imm & 0xFFF, rs1, 0x0, rd, 0x03)
def rv_lh(rd, rs1, imm):     return encode_i(imm & 0xFFF, rs1, 0x1, rd, 0x03)
def rv_lw(rd, rs1, imm):     return encode_i(imm & 0xFFF, rs1, 0x2, rd, 0x03)
def rv_ld(rd, rs1, imm):     return encode_i(imm & 0xFFF, rs1, 0x3, rd, 0x03)
def rv_lbu(rd, rs1, imm):    return encode_i(imm & 0xFFF, rs1, 0x4, rd, 0x03)
def rv_lhu(rd, rs1, imm):    return encode_i(imm & 0xFFF, rs1, 0x5, rd, 0x03)

def rv_sb(rs2, rs1, imm):    return encode_s(imm & 0xFFF, rs2, rs1, 0x0)
def rv_sh(rs2, rs1, imm):    return encode_s(imm & 0xFFF, rs2, rs1, 0x1)
def rv_sw(rs2, rs1, imm):    return encode_s(imm & 0xFFF, rs2, rs1, 0x2)
def rv_sd(rs2, rs1, imm):    return encode_s(imm & 0xFFF, rs2, rs1, 0x3)

def rv_beq(rs1, rs2, off):   return encode_b(off, rs1, rs2, 0x0)
def rv_bne(rs1, rs2, off):   return encode_b(off, rs1, rs2, 0x1)
def rv_blt(rs1, rs2, off):   return encode_b(off, rs1, rs2, 0x4)
def rv_bge(rs1, rs2, off):   return encode_b(off, rs1, rs2, 0x5)
def rv_bltu(rs1, rs2, off):  return encode_b(off, rs1, rs2, 0x6)
def rv_bgeu(rs1, rs2, off):  return encode_b(off, rs1, rs2, 0x7)

def rv_jal(rd, off):         return encode_j(off, rd)
def rv_jalr(rd, rs1, imm):   return encode_i(imm & 0xFFF, rs1, 0x0, rd, 0x67)
def rv_lui(rd, imm20):       return encode_u(imm20, rd, 0x37)
def rv_auipc(rd, imm20):     return encode_u(imm20, rd, 0x17)

def rv_nop():                return rv_addi(0, 0, 0)  # addi x0, x0, 0


# =============================================================================
# ARM Register Mapping
# =============================================================================

# ARM r0-r15 -> RV64I register numbers
ARM_TO_RV = {
    'r0': 10, 'r1': 11, 'r2': 12, 'r3': 13,
    'r4': 14, 'r5': 15, 'r6': 16, 'r7': 17,
    'r8': 18, 'r9': 19, 'r10': 20, 'r11': 21,
    'r12': 22,
    'sp': 2, 'r13': 2,       # stack pointer
    'lr': 1, 'r14': 1,       # link register
    'fp': 8,                   # frame pointer (r11 alias)
    'ip': 22,                  # intra-procedure scratch (r12 alias)
    'pc': -1,                  # program counter (special)
}

# RV64I temp registers for scratch use during translation
RV_TEMP1 = 30  # x30 (t5) - translator scratch 1
RV_TEMP2 = 29  # x29 (t4) - translator scratch 2
RV_ZERO  = 0   # x0


# =============================================================================
# ARM Instruction Parser
# =============================================================================

@dataclass
class ARMInstruction:
    """Parsed ARM instruction"""
    label: str = ""
    opcode: str = ""
    cond: str = ""            # condition code: eq, ne, lt, ge, gt, le, etc.
    s_flag: bool = False      # 'S' suffix (updates flags)
    operands: list = field(default_factory=list)
    comment: str = ""
    raw: str = ""
    line_num: int = 0
    is_directive: bool = False
    is_label: bool = False


def parse_arm_register(s: str) -> str:
    """Normalize ARM register name"""
    s = s.strip().lower()
    # Handle aliases
    aliases = {'a1': 'r0', 'a2': 'r1', 'a3': 'r2', 'a4': 'r3',
               'v1': 'r4', 'v2': 'r5', 'v3': 'r6', 'v4': 'r7',
               'v5': 'r8', 'sb': 'r9', 'sl': 'r10', 'fp': 'fp',
               'ip': 'ip', 'sp': 'sp', 'lr': 'lr', 'pc': 'pc'}
    return aliases.get(s, s)


def parse_immediate(s: str) -> int:
    """Parse ARM immediate value: #123, #0xFF, #-5"""
    s = s.strip().lstrip('#')
    if s.startswith('0x') or s.startswith('0X'):
        return int(s, 16)
    elif s.startswith('-0x') or s.startswith('-0X'):
        return -int(s[1:], 16)
    else:
        return int(s)


def parse_arm_line(line: str, line_num: int) -> Optional[ARMInstruction]:
    """Parse a single line of ARM assembly"""
    inst = ARMInstruction(raw=line, line_num=line_num)

    # Strip comment
    if '@' in line:
        idx = line.index('@')
        inst.comment = line[idx:]
        line = line[:idx]
    if '//' in line:
        idx = line.index('//')
        inst.comment = line[idx:]
        line = line[:idx]

    line = line.strip()
    if not line:
        return None

    # Check for label
    if line.endswith(':'):
        inst.label = line[:-1].strip()
        inst.is_label = True
        return inst

    # Detect label: at start of line
    m = re.match(r'^(\w+):\s*(.*)', line)
    if m:
        inst.label = m.group(1)
        line = m.group(2).strip()
        if not line:
            inst.is_label = True
            return inst

    # Directives
    if line.startswith('.'):
        inst.opcode = line
        inst.is_directive = True
        return inst

    # Data directive (.word)
    if line.startswith('.word'):
        inst.opcode = '.word'
        inst.operands = [line[5:].strip()]
        inst.is_directive = True
        return inst

    # Parse instruction
    parts = line.split(None, 1)
    if not parts:
        return None

    mnemonic = parts[0].lower()
    operand_str = parts[1] if len(parts) > 1 else ""

    # Extract condition code and S flag
    cond_codes = ['eq', 'ne', 'cs', 'hs', 'cc', 'lo', 'mi', 'pl',
                  'vs', 'vc', 'hi', 'ls', 'ge', 'lt', 'gt', 'le', 'al']

    # Special handling for known mnemonics that end with condition-like suffixes
    base_opcodes = ['add', 'sub', 'rsb', 'adc', 'sbc', 'rsc',
                    'and', 'orr', 'eor', 'bic', 'mvn', 'mov',
                    'cmp', 'cmn', 'tst', 'teq',
                    'ldr', 'str', 'ldm', 'stm', 'lsl', 'lsr', 'asr',
                    'mul', 'mla',
                    'push', 'pop',
                    'b', 'bl', 'bx', 'blx',
                    'nop', 'swi', 'svc']

    inst.cond = ''
    inst.s_flag = False

    # Try to match base opcode
    matched = False
    for base in sorted(base_opcodes, key=len, reverse=True):
        if mnemonic.startswith(base):
            rest = mnemonic[len(base):]
            inst.opcode = base

            # Check for condition code
            for cc in cond_codes:
                if rest.startswith(cc):
                    inst.cond = cc
                    rest = rest[len(cc):]
                    break

            # Check for S flag
            if rest == 's':
                inst.s_flag = True
                rest = ''

            # Handle ldr/str variants: ldrb, ldrh, strb, strh
            if base in ('ldr', 'str') and rest in ('b', 'h', 'sb', 'sh'):
                inst.opcode = base + rest
                rest = ''

            # ldmia, stmia etc
            if base in ('ldm', 'stm') and rest in ('ia', 'ib', 'da', 'db',
                                                     'ia!', 'ib!', 'da!', 'db!'):
                inst.opcode = base + rest.rstrip('!')
                rest = ''

            if rest == '' or rest == 's':
                if rest == 's':
                    inst.s_flag = True
                matched = True
                break

    if not matched:
        # Fallback: treat entire mnemonic as opcode
        inst.opcode = mnemonic

    # Parse operands
    if operand_str:
        # Handle register list {r0, r1, r2, r3}
        if '{' in operand_str:
            # Split before and after the braces
            pre = operand_str[:operand_str.index('{')].strip().rstrip(',')
            brace_content = operand_str[operand_str.index('{')+1:operand_str.index('}')]
            post = operand_str[operand_str.index('}')+1:].strip()

            if pre:
                inst.operands.append(pre.strip())
            inst.operands.append('{' + brace_content + '}')
            if post and post != '!':
                inst.operands.append(post)
            if '!' in operand_str:
                inst.operands.append('!')
        else:
            # Handle [base, #offset] memory operands
            # Split by comma, but not inside brackets
            ops = []
            depth = 0
            current = ''
            for ch in operand_str:
                if ch == '[':
                    depth += 1
                    current += ch
                elif ch == ']':
                    depth -= 1
                    current += ch
                elif ch == ',' and depth == 0:
                    ops.append(current.strip())
                    current = ''
                else:
                    current += ch
            if current.strip():
                ops.append(current.strip())
            inst.operands = ops

    return inst


def parse_register_list(s: str) -> List[str]:
    """Parse ARM register list: {r0, r1, r2-r5, lr}"""
    s = s.strip('{}').strip()
    regs = []
    for part in s.split(','):
        part = part.strip()
        if '-' in part:
            # Range: r2-r5
            start, end = part.split('-')
            start = start.strip()
            end = end.strip()
            start_num = int(re.search(r'\d+', start).group())
            end_num = int(re.search(r'\d+', end).group())
            for i in range(start_num, end_num + 1):
                regs.append(f'r{i}')
        else:
            regs.append(parse_arm_register(part))
    return regs


def parse_memory_operand(s: str) -> Tuple[str, int, bool]:
    """Parse ARM memory operand: [r3, #-52] -> (reg, offset, pre_index)
    Returns (base_reg, offset, writeback)"""
    s = s.strip()
    # [reg, #imm]
    m = re.match(r'\[(\w+),\s*#(-?\w+)\](!)?', s)
    if m:
        return parse_arm_register(m.group(1)), parse_immediate(m.group(2)), m.group(3) == '!'
    # [reg]
    m = re.match(r'\[(\w+)\](!)?', s)
    if m:
        return parse_arm_register(m.group(1)), 0, m.group(2) == '!'
    # Just a register (for ldm/stm)
    return parse_arm_register(s), 0, False


# =============================================================================
# ARM -> RV64I Translator
# =============================================================================

@dataclass
class RV64Instruction:
    """Generated RV64I instruction"""
    asm: str            # Assembly text
    machine_code: int   # 32-bit machine code
    comment: str = ""   # Comment explaining the translation
    address: int = 0    # Byte address


class ARM2RV64Translator:
    """Translates ARM assembly to RV64I"""

    def __init__(self, data_width=64, base_addr=0):
        self.labels: Dict[str, int] = {}      # label -> RV64I instruction index
        self.rv_instructions: List[RV64Instruction] = []
        self.arm_instructions: List[ARMInstruction] = []
        self.data_width = data_width           # 32 or 64 bit data words
        self.base_addr = base_addr
        self.word_size = data_width // 8       # bytes per word (4 or 8)

        # For condition code translation: ARM uses flags (N,Z,C,V)
        # We track which registers hold the last CMP operands
        self.cmp_rs1 = -1
        self.cmp_rs2 = -1

    def arm_reg(self, name: str) -> int:
        """Convert ARM register name to RV64I register number"""
        name = parse_arm_register(name)
        if name in ARM_TO_RV:
            rv = ARM_TO_RV[name]
            if rv < 0:
                raise ValueError(f"Cannot directly use ARM register '{name}' in RV64I")
            return rv
        raise ValueError(f"Unknown ARM register: '{name}'")

    def emit(self, asm: str, machine_code: int, comment: str = ""):
        """Add a RV64I instruction"""
        idx = len(self.rv_instructions)
        addr = self.base_addr + idx * 4
        self.rv_instructions.append(RV64Instruction(
            asm=asm, machine_code=machine_code & 0xFFFFFFFF,
            comment=comment, address=addr
        ))

    def emit_li(self, rd: int, imm: int):
        """Load immediate (handles values outside 12-bit range using LUI+ADDI)"""
        if -2048 <= imm <= 2047:
            self.emit(f"addi x{rd}, x0, {imm}", rv_addi(rd, 0, imm),
                      f"li x{rd}, {imm}")
        else:
            # LUI + ADDI for larger immediates
            upper = (imm + 0x800) >> 12
            lower = imm - (upper << 12)
            self.emit(f"lui x{rd}, {upper & 0xFFFFF}", rv_lui(rd, upper & 0xFFFFF),
                      f"li x{rd}, {imm} (upper)")
            if lower != 0:
                self.emit(f"addi x{rd}, x{rd}, {lower}", rv_addi(rd, rd, lower & 0xFFF),
                          f"li x{rd}, {imm} (lower)")

    # ----- Pass 1: Parse ARM assembly and collect labels -----

    def parse(self, lines: List[str]):
        """Parse ARM assembly, first pass: collect labels and instructions"""
        for i, line in enumerate(lines):
            inst = parse_arm_line(line, i + 1)
            if inst:
                self.arm_instructions.append(inst)

    # ----- Pass 2: Translate to RV64I (label-unresolved) -----

    def translate(self):
        """Two-pass translation"""
        # Pass 1: Generate RV64I instructions, record label positions
        # We need to know how many RV64I instructions each ARM instruction generates
        # to compute label addresses. Do a dry run first.

        # Collect ARM labels and their indices
        arm_labels = {}
        arm_code = []  # (arm_index, instruction)
        for inst in self.arm_instructions:
            if inst.is_label:
                arm_labels[inst.label] = len(arm_code)
            elif inst.is_directive:
                continue
            else:
                arm_code.append(inst)
                if inst.label:
                    arm_labels[inst.label] = len(arm_code) - 1

        # First pass: translate without resolving branch targets
        # to count RV64I instructions per ARM instruction
        rv_counts = []  # how many RV64I instructions per ARM instruction
        arm_to_rv_start = []  # starting RV64I index for each ARM instruction

        for arm_idx, inst in enumerate(arm_code):
            start = len(self.rv_instructions)
            arm_to_rv_start.append(start)
            self._translate_one(inst, resolve_branches=False)
            rv_counts.append(len(self.rv_instructions) - start)

        # Build label -> RV64I address mapping
        for label, arm_idx in arm_labels.items():
            if arm_idx < len(arm_to_rv_start):
                rv_idx = arm_to_rv_start[arm_idx]
                self.labels[label] = self.base_addr + rv_idx * 4
            else:
                # Label after last instruction
                self.labels[label] = self.base_addr + len(self.rv_instructions) * 4

        # Second pass: regenerate with resolved branches
        self.rv_instructions.clear()
        arm_to_rv_start.clear()

        for arm_idx, inst in enumerate(arm_code):
            arm_to_rv_start.append(len(self.rv_instructions))
            self._translate_one(inst, resolve_branches=True)

        # Update label mapping with final addresses
        for label, arm_idx in arm_labels.items():
            if arm_idx < len(arm_to_rv_start):
                rv_idx = arm_to_rv_start[arm_idx]
                self.labels[label] = self.base_addr + rv_idx * 4
            else:
                self.labels[label] = self.base_addr + len(self.rv_instructions) * 4

        # Third pass: fix up branch offsets with final label positions
        self.rv_instructions.clear()
        arm_to_rv_start.clear()

        for arm_idx, inst in enumerate(arm_code):
            arm_to_rv_start.append(len(self.rv_instructions))
            self._translate_one(inst, resolve_branches=True)

        # Final label update
        for label, arm_idx in arm_labels.items():
            if arm_idx < len(arm_to_rv_start):
                rv_idx = arm_to_rv_start[arm_idx]
                self.labels[label] = self.base_addr + rv_idx * 4
            else:
                self.labels[label] = self.base_addr + len(self.rv_instructions) * 4

    def _get_branch_offset(self, target_label: str) -> int:
        """Get byte offset from current instruction to target label"""
        current_addr = self.base_addr + len(self.rv_instructions) * 4
        if target_label in self.labels:
            return self.labels[target_label] - current_addr
        return 0  # placeholder

    def _translate_one(self, inst: ARMInstruction, resolve_branches: bool = False):
        """Translate one ARM instruction to RV64I"""
        op = inst.opcode
        ops = inst.operands
        cond = inst.cond

        try:
            # Handle conditional execution
            if cond and op not in ('b', 'bl', 'bx', 'blx') and cond != 'al':
                self._translate_conditional(inst, resolve_branches)
                return

            if op == 'nop':
                self.emit("addi x0, x0, 0", rv_nop(), "nop")

            elif op == 'mov':
                rd = self.arm_reg(ops[0])
                if ops[1].startswith('#'):
                    imm = parse_immediate(ops[1])
                    self.emit_li(rd, imm)
                else:
                    rs = self.arm_reg(ops[1])
                    self.emit(f"addi x{rd}, x{rs}, 0", rv_addi(rd, rs, 0),
                              f"mov {ops[0]}, {ops[1]}")

            elif op == 'mvn':
                rd = self.arm_reg(ops[0])
                if ops[1].startswith('#'):
                    imm = parse_immediate(ops[1])
                    self.emit_li(rd, ~imm)
                else:
                    rs = self.arm_reg(ops[1])
                    self.emit(f"xori x{rd}, x{rs}, -1", rv_xori(rd, rs, -1),
                              f"mvn {ops[0]}, {ops[1]}")

            elif op == 'add':
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                if len(ops) > 2 and ops[2].startswith('#'):
                    imm = parse_immediate(ops[2])
                    if -2048 <= imm <= 2047:
                        self.emit(f"addi x{rd}, x{rs1}, {imm}", rv_addi(rd, rs1, imm),
                                  f"add {ops[0]}, {ops[1]}, {ops[2]}")
                    else:
                        self.emit_li(RV_TEMP1, imm)
                        self.emit(f"add x{rd}, x{rs1}, x{RV_TEMP1}",
                                  rv_add(rd, rs1, RV_TEMP1),
                                  f"add {ops[0]}, {ops[1]}, {ops[2]}")
                elif len(ops) > 2:
                    rs2 = self.arm_reg(ops[2])
                    # Check for shifted operand: add rd, rs1, rs2, lsl #n
                    if len(ops) > 3:
                        self._translate_shifted_op('add', rd, rs1, rs2, ops[3])
                    else:
                        self.emit(f"add x{rd}, x{rs1}, x{rs2}", rv_add(rd, rs1, rs2),
                                  f"add {ops[0]}, {ops[1]}, {ops[2]}")
                else:
                    # Two-operand form: add rd, rs1 → add rd, rd, rs1
                    self.emit(f"add x{rd}, x{rd}, x{rs1}", rv_add(rd, rd, rs1),
                              f"add {ops[0]}, {ops[1]}")

            elif op == 'sub':
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                if len(ops) > 2 and ops[2].startswith('#'):
                    imm = parse_immediate(ops[2])
                    neg_imm = -imm
                    if -2048 <= neg_imm <= 2047:
                        self.emit(f"addi x{rd}, x{rs1}, {neg_imm}",
                                  rv_addi(rd, rs1, neg_imm),
                                  f"sub {ops[0]}, {ops[1]}, {ops[2]}")
                    else:
                        self.emit_li(RV_TEMP1, imm)
                        self.emit(f"sub x{rd}, x{rs1}, x{RV_TEMP1}",
                                  rv_sub(rd, rs1, RV_TEMP1),
                                  f"sub {ops[0]}, {ops[1]}, {ops[2]}")
                elif len(ops) > 2:
                    rs2 = self.arm_reg(ops[2])
                    self.emit(f"sub x{rd}, x{rs1}, x{rs2}", rv_sub(rd, rs1, rs2),
                              f"sub {ops[0]}, {ops[1]}, {ops[2]}")

            elif op == 'rsb':
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                if len(ops) > 2 and ops[2].startswith('#'):
                    imm = parse_immediate(ops[2])
                    if imm == 0:
                        self.emit(f"sub x{rd}, x0, x{rs1}", rv_sub(rd, 0, rs1),
                                  f"rsb {ops[0]}, {ops[1]}, #0 (negate)")
                    else:
                        self.emit_li(RV_TEMP1, imm)
                        self.emit(f"sub x{rd}, x{RV_TEMP1}, x{rs1}",
                                  rv_sub(rd, RV_TEMP1, rs1),
                                  f"rsb {ops[0]}, {ops[1]}, {ops[2]}")

            elif op in ('and', 'orr', 'eor', 'bic'):
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                if len(ops) > 2 and ops[2].startswith('#'):
                    imm = parse_immediate(ops[2])
                    if op == 'bic':
                        imm = ~imm
                        op_actual = 'and'
                    else:
                        op_actual = op
                    if op_actual == 'and':
                        self.emit_li(RV_TEMP1, imm)
                        self.emit(f"and x{rd}, x{rs1}, x{RV_TEMP1}",
                                  rv_and(rd, rs1, RV_TEMP1), f"{op} imm")
                    elif op_actual == 'orr':
                        if -2048 <= imm <= 2047:
                            self.emit(f"ori x{rd}, x{rs1}, {imm}",
                                      rv_ori(rd, rs1, imm), f"orr imm")
                        else:
                            self.emit_li(RV_TEMP1, imm)
                            self.emit(f"or x{rd}, x{rs1}, x{RV_TEMP1}",
                                      rv_or(rd, rs1, RV_TEMP1), f"orr imm")
                    elif op_actual == 'eor':
                        if -2048 <= imm <= 2047:
                            self.emit(f"xori x{rd}, x{rs1}, {imm}",
                                      rv_xori(rd, rs1, imm), f"eor imm")
                        else:
                            self.emit_li(RV_TEMP1, imm)
                            self.emit(f"xor x{rd}, x{rs1}, x{RV_TEMP1}",
                                      rv_xor(rd, rs1, RV_TEMP1), f"eor imm")
                elif len(ops) > 2:
                    rs2 = self.arm_reg(ops[2])
                    func_map = {'and': rv_and, 'orr': rv_or, 'eor': rv_xor}
                    if op == 'bic':
                        # rd = rs1 & ~rs2  → xori tmp, rs2, -1; and rd, rs1, tmp
                        self.emit(f"xori x{RV_TEMP1}, x{rs2}, -1",
                                  rv_xori(RV_TEMP1, rs2, -1), "bic: ~rs2")
                        self.emit(f"and x{rd}, x{rs1}, x{RV_TEMP1}",
                                  rv_and(rd, rs1, RV_TEMP1), "bic: and")
                    else:
                        rv_func = func_map[op]
                        self.emit(f"{op} x{rd}, x{rs1}, x{rs2}",
                                  rv_func(rd, rs1, rs2), f"{op}")

            elif op == 'lsl':
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                if len(ops) > 2 and ops[2].startswith('#'):
                    shamt = parse_immediate(ops[2])
                    self.emit(f"slli x{rd}, x{rs1}, {shamt}", rv_slli(rd, rs1, shamt),
                              f"lsl {ops[0]}, {ops[1]}, {ops[2]}")
                elif len(ops) > 2:
                    rs2 = self.arm_reg(ops[2])
                    self.emit(f"sll x{rd}, x{rs1}, x{rs2}", rv_sll(rd, rs1, rs2),
                              f"lsl {ops[0]}, {ops[1]}, {ops[2]}")
                else:
                    # Two-operand: lsl rd, #n (implicit same register)
                    shamt = parse_immediate(ops[1])
                    self.emit(f"slli x{rd}, x{rd}, {shamt}", rv_slli(rd, rd, shamt))

            elif op == 'lsr':
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                if len(ops) > 2 and ops[2].startswith('#'):
                    shamt = parse_immediate(ops[2])
                    self.emit(f"srli x{rd}, x{rs1}, {shamt}", rv_srli(rd, rs1, shamt))
                elif len(ops) > 2:
                    rs2 = self.arm_reg(ops[2])
                    self.emit(f"srl x{rd}, x{rs1}, x{rs2}", rv_srl(rd, rs1, rs2))

            elif op == 'asr':
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                if len(ops) > 2 and ops[2].startswith('#'):
                    shamt = parse_immediate(ops[2])
                    self.emit(f"srai x{rd}, x{rs1}, {shamt}", rv_srai(rd, rs1, shamt))
                elif len(ops) > 2:
                    rs2 = self.arm_reg(ops[2])
                    self.emit(f"sra x{rd}, x{rs1}, x{rs2}", rv_sra(rd, rs1, rs2))

            elif op == 'mul':
                # RV64I doesn't have MUL. Implement with shift-and-add or
                # just emit a placeholder. For the lab, we use RV64M extension
                # or implement with a loop. Here we'll note it.
                rd = self.arm_reg(ops[0])
                rs1 = self.arm_reg(ops[1])
                rs2 = self.arm_reg(ops[2]) if len(ops) > 2 else self.arm_reg(ops[1])
                # Placeholder: emit a comment
                self.emit(f"# MUL x{rd}, x{rs1}, x{rs2} (requires M extension)",
                          rv_nop(), "WARNING: MUL not in base RV64I")

            elif op == 'cmp':
                # CMP sets flags based on rs1 - rs2.
                # In RV64I, we save the operands for the next conditional branch
                rs1 = self.arm_reg(ops[0])
                if ops[1].startswith('#'):
                    imm = parse_immediate(ops[1])
                    # Store: cmp_rs1 = rs1, cmp_rs2 = temp with imm loaded
                    self.emit_li(RV_TEMP1, imm)
                    self.cmp_rs1 = rs1
                    self.cmp_rs2 = RV_TEMP1
                else:
                    rs2 = self.arm_reg(ops[1])
                    self.cmp_rs1 = rs1
                    self.cmp_rs2 = rs2
                    # No instruction needed; the branch will use rs1/rs2 directly

            elif op == 'cmn':
                # CMN: compare negative (rs1 + rs2 vs 0)
                rs1 = self.arm_reg(ops[0])
                if ops[1].startswith('#'):
                    imm = parse_immediate(ops[1])
                    self.emit_li(RV_TEMP1, -imm)
                else:
                    rs2 = self.arm_reg(ops[1])
                    self.emit(f"sub x{RV_TEMP1}, x0, x{rs2}", rv_sub(RV_TEMP1, 0, rs2))
                self.cmp_rs1 = rs1
                self.cmp_rs2 = RV_TEMP1

            elif op in ('ldr', 'ldrb', 'ldrh', 'ldrsb', 'ldrsh'):
                rd = self.arm_reg(ops[0])
                base_reg, offset, wb = parse_memory_operand(ops[1])
                rs1 = self.arm_reg(base_reg)

                # Handle pc-relative loads (literal pool)
                if base_reg == 'pc':
                    # Can't do PC-relative in simple translation, use label
                    self.emit(f"# PC-relative load - needs manual fixup", rv_nop(),
                              f"ldr {ops[0]}, {ops[1]}")
                    return

                if op == 'ldr':
                    self.emit(f"lw x{rd}, {offset}(x{rs1})", rv_lw(rd, rs1, offset),
                              f"ldr {ops[0]}, {ops[1]}")
                elif op == 'ldrb':
                    self.emit(f"lbu x{rd}, {offset}(x{rs1})", rv_lbu(rd, rs1, offset),
                              f"ldrb {ops[0]}, {ops[1]}")
                elif op == 'ldrh':
                    self.emit(f"lhu x{rd}, {offset}(x{rs1})", rv_lhu(rd, rs1, offset),
                              f"ldrh {ops[0]}, {ops[1]}")
                elif op == 'ldrsb':
                    self.emit(f"lb x{rd}, {offset}(x{rs1})", rv_lb(rd, rs1, offset),
                              f"ldrsb")
                elif op == 'ldrsh':
                    self.emit(f"lh x{rd}, {offset}(x{rs1})", rv_lh(rd, rs1, offset),
                              f"ldrsh")

                if wb:
                    self.emit(f"addi x{rs1}, x{rs1}, {offset}",
                              rv_addi(rs1, rs1, offset), "writeback")

            elif op in ('str', 'strb', 'strh'):
                rd = self.arm_reg(ops[0])
                base_reg, offset, wb = parse_memory_operand(ops[1])
                rs1 = self.arm_reg(base_reg)

                if op == 'str':
                    self.emit(f"sw x{rd}, {offset}(x{rs1})", rv_sw(rd, rs1, offset),
                              f"str {ops[0]}, {ops[1]}")
                elif op == 'strb':
                    self.emit(f"sb x{rd}, {offset}(x{rs1})", rv_sb(rd, rs1, offset),
                              f"strb")
                elif op == 'strh':
                    self.emit(f"sh x{rd}, {offset}(x{rs1})", rv_sh(rd, rs1, offset),
                              f"strh")

                if wb:
                    self.emit(f"addi x{rs1}, x{rs1}, {offset}",
                              rv_addi(rs1, rs1, offset), "writeback")

            elif op in ('ldmia', 'ldm', 'stmia', 'stm'):
                # Multi load/store: expand to individual ld/sd
                base_reg_str = ops[0].rstrip('!')
                writeback = '!' in ops[0] or '!' in ops
                base_rv = self.arm_reg(base_reg_str)
                reg_list = parse_register_list(ops[1])

                offset = 0
                for reg_name in reg_list:
                    rv_reg = self.arm_reg(reg_name)
                    if op.startswith('ldm') or op.startswith('ld'):
                        self.emit(f"lw x{rv_reg}, {offset}(x{base_rv})",
                                  rv_lw(rv_reg, base_rv, offset),
                                  f"ldmia {reg_name}")
                    else:
                        self.emit(f"sw x{rv_reg}, {offset}(x{base_rv})",
                                  rv_sw(rv_reg, base_rv, offset),
                                  f"stmia {reg_name}")
                    offset += 4  # ARM uses 32-bit words

                if writeback:
                    self.emit(f"addi x{base_rv}, x{base_rv}, {offset}",
                              rv_addi(base_rv, base_rv, offset),
                              "ldmia/stmia writeback")

            elif op == 'push':
                reg_list = parse_register_list(ops[0])
                # push: sp -= 4*n, then store
                n = len(reg_list)
                self.emit(f"addi x2, x2, {-4 * n}", rv_addi(2, 2, -4 * n), "push: adjust sp")
                for i, reg_name in enumerate(reg_list):
                    rv_reg = self.arm_reg(reg_name)
                    offset = i * 4
                    self.emit(f"sw x{rv_reg}, {offset}(x2)", rv_sw(rv_reg, 2, offset),
                              f"push {reg_name}")

            elif op == 'pop':
                reg_list = parse_register_list(ops[0])
                n = len(reg_list)
                for i, reg_name in enumerate(reg_list):
                    rv_reg = self.arm_reg(reg_name)
                    offset = i * 4
                    self.emit(f"lw x{rv_reg}, {offset}(x2)", rv_lw(rv_reg, 2, offset),
                              f"pop {reg_name}")
                self.emit(f"addi x2, x2, {4 * n}", rv_addi(2, 2, 4 * n), "pop: adjust sp")

            elif op == 'b':
                target = ops[0] if ops else ""
                if cond:
                    self._translate_branch(cond, target, resolve_branches)
                else:
                    if resolve_branches and target in self.labels:
                        offset = self._get_branch_offset(target)
                        self.emit(f"jal x0, {target}", rv_jal(0, offset),
                                  f"b {target}")
                    else:
                        self.emit(f"jal x0, {target}", rv_jal(0, 0), f"b {target}")

            elif op == 'bl':
                target = ops[0] if ops else ""
                if resolve_branches and target in self.labels:
                    offset = self._get_branch_offset(target)
                    self.emit(f"jal x1, {target}", rv_jal(1, offset), f"bl {target}")
                else:
                    self.emit(f"jal x1, {target}", rv_jal(1, 0), f"bl {target}")

            elif op == 'bx':
                rs = self.arm_reg(ops[0])
                self.emit(f"jalr x0, x{rs}, 0", rv_jalr(0, rs, 0), f"bx {ops[0]}")

            elif op == 'blx':
                rs = self.arm_reg(ops[0])
                self.emit(f"jalr x1, x{rs}, 0", rv_jalr(1, rs, 0), f"blx {ops[0]}")

            else:
                # Unknown instruction - emit as comment
                self.emit(f"# UNKNOWN: {inst.raw.strip()}", rv_nop(),
                          f"UNHANDLED: {op}")

        except Exception as e:
            self.emit(f"# ERROR translating: {inst.raw.strip()} ({e})", rv_nop(),
                      f"ERROR: {e}")

    def _translate_branch(self, cond: str, target: str, resolve: bool):
        """Translate ARM conditional branch using saved CMP operands"""
        rs1 = self.cmp_rs1
        rs2 = self.cmp_rs2

        if rs1 < 0 or rs2 < 0:
            self.emit(f"# WARNING: branch without prior CMP", rv_nop())
            return

        if resolve and target in self.labels:
            offset = self._get_branch_offset(target)
        else:
            offset = 0

        # Map ARM condition to RV64I branch
        if cond == 'eq':
            self.emit(f"beq x{rs1}, x{rs2}, {target}", rv_beq(rs1, rs2, offset), f"beq")
        elif cond == 'ne':
            self.emit(f"bne x{rs1}, x{rs2}, {target}", rv_bne(rs1, rs2, offset), f"bne")
        elif cond in ('ge', 'hs'):  # signed >=
            self.emit(f"bge x{rs1}, x{rs2}, {target}", rv_bge(rs1, rs2, offset), f"bge")
        elif cond in ('lt', 'lo'):  # signed <
            self.emit(f"blt x{rs1}, x{rs2}, {target}", rv_blt(rs1, rs2, offset), f"blt")
        elif cond == 'gt':  # signed >: use blt with swapped operands
            self.emit(f"blt x{rs2}, x{rs1}, {target}", rv_blt(rs2, rs1, offset), f"bgt→blt")
        elif cond == 'le':  # signed <=: use bge with swapped operands
            self.emit(f"bge x{rs2}, x{rs1}, {target}", rv_bge(rs2, rs1, offset), f"ble→bge")
        elif cond == 'hi':  # unsigned >
            self.emit(f"bltu x{rs2}, x{rs1}, {target}", rv_bltu(rs2, rs1, offset), f"bhi→bltu")
        elif cond == 'ls':  # unsigned <=
            self.emit(f"bgeu x{rs2}, x{rs1}, {target}", rv_bgeu(rs2, rs1, offset), f"bls→bgeu")
        elif cond == 'cs':  # carry set (unsigned >=)
            self.emit(f"bgeu x{rs1}, x{rs2}, {target}", rv_bgeu(rs1, rs2, offset), f"bcs→bgeu")
        elif cond == 'cc':  # carry clear (unsigned <)
            self.emit(f"bltu x{rs1}, x{rs2}, {target}", rv_bltu(rs1, rs2, offset), f"bcc→bltu")
        else:
            self.emit(f"# UNSUPPORTED condition: {cond}", rv_nop())

    def _translate_conditional(self, inst: ARMInstruction, resolve: bool):
        """Translate conditionally executed ARM instruction (non-branch).
        Strategy: emit branch to skip the instruction if condition is NOT met."""
        # This is a simplification. A full implementation would handle
        # all condition codes properly.
        cond = inst.cond
        rs1 = self.cmp_rs1
        rs2 = self.cmp_rs2

        if rs1 < 0 or rs2 < 0:
            # No CMP context, just emit unconditionally
            inst_copy = ARMInstruction(**{k: v for k, v in inst.__dict__.items()})
            inst_copy.cond = ''
            self._translate_one(inst_copy, resolve)
            return

        # Save current position, emit instruction unconditionally, count size
        save_len = len(self.rv_instructions)

        inst_copy = ARMInstruction(**{k: v for k, v in inst.__dict__.items()})
        inst_copy.cond = ''
        self._translate_one(inst_copy, resolve)
        n_instr = len(self.rv_instructions) - save_len

        # Now re-emit with conditional skip
        # Remove the instructions we just generated
        generated = self.rv_instructions[save_len:]
        self.rv_instructions = self.rv_instructions[:save_len]

        # Emit inverse-condition branch to skip
        skip_offset = (n_instr + 1) * 4  # +1 for the branch itself
        inv_cond_map = {
            'eq': ('bne', rv_bne), 'ne': ('beq', rv_beq),
            'ge': ('blt', rv_blt), 'lt': ('bge', rv_bge),
            'gt': ('bge', rv_bge), 'le': ('blt', rv_blt),
            'hi': ('bgeu', rv_bgeu), 'ls': ('bltu', rv_bltu),
            'cs': ('bltu', rv_bltu), 'cc': ('bgeu', rv_bgeu),
        }

        if cond in inv_cond_map:
            name, func = inv_cond_map[cond]
            if cond in ('gt', 'le'):
                self.emit(f"{name} x{rs2}, x{rs1}, +{skip_offset}",
                          func(rs2, rs1, skip_offset), f"skip if NOT {cond}")
            else:
                self.emit(f"{name} x{rs1}, x{rs2}, +{skip_offset}",
                          func(rs1, rs2, skip_offset), f"skip if NOT {cond}")
        else:
            self.emit(f"# UNSUPPORTED cond exec: {cond}", rv_nop())

        # Re-emit the actual instruction
        for gi in generated:
            self.rv_instructions.append(gi)

    def _translate_shifted_op(self, op, rd, rs1, rs2, shift_str):
        """Handle ARM shifted register operand: add rd, rs1, rs2, lsl #3"""
        shift_str = shift_str.strip()
        m = re.match(r'(lsl|lsr|asr)\s+#(\d+)', shift_str)
        if m:
            shift_type = m.group(1)
            shamt = int(m.group(2))
            # Shift rs2 into temp, then do the operation
            if shift_type == 'lsl':
                self.emit(f"slli x{RV_TEMP1}, x{rs2}, {shamt}",
                          rv_slli(RV_TEMP1, rs2, shamt), f"{shift_str}")
            elif shift_type == 'lsr':
                self.emit(f"srli x{RV_TEMP1}, x{rs2}, {shamt}",
                          rv_srli(RV_TEMP1, rs2, shamt), f"{shift_str}")
            elif shift_type == 'asr':
                self.emit(f"srai x{RV_TEMP1}, x{rs2}, {shamt}",
                          rv_srai(RV_TEMP1, rs2, shamt), f"{shift_str}")

            if op == 'add':
                self.emit(f"add x{rd}, x{rs1}, x{RV_TEMP1}",
                          rv_add(rd, rs1, RV_TEMP1), f"add with shifted reg")
            elif op == 'sub':
                self.emit(f"sub x{rd}, x{rs1}, x{RV_TEMP1}",
                          rv_sub(rd, rs1, RV_TEMP1), f"sub with shifted reg")

    # ----- Output Generation -----

    def get_hex(self) -> str:
        """Generate hex file (one word per line)"""
        lines = []
        for inst in self.rv_instructions:
            lines.append(f"{inst.machine_code:08X}")
        return '\n'.join(lines)

    def get_asm(self) -> str:
        """Generate annotated RV64I assembly"""
        lines = []
        # Print label positions
        label_addrs = {v: k for k, v in self.labels.items()}

        for inst in self.rv_instructions:
            if inst.address in label_addrs:
                lines.append(f"{label_addrs[inst.address]}:")
            comment = f"  # {inst.comment}" if inst.comment else ""
            lines.append(f"    {inst.asm}{comment}")
        return '\n'.join(lines)

    def get_verilog(self, mem_name="u_instr_mem.mem") -> str:
        """Generate Verilog memory initialization statements"""
        lines = []
        label_addrs = {v: k for k, v in self.labels.items()}

        for i, inst in enumerate(self.rv_instructions):
            label_comment = ""
            if inst.address in label_addrs:
                label_comment = f"  // {label_addrs[inst.address]}:"

            comment = f"  // {inst.asm}"
            if inst.comment:
                comment += f"  ({inst.comment})"

            lines.append(
                f"        dut.{mem_name}[{i:3d}] = 32'h{inst.machine_code:08X};{label_comment}{comment}"
            )
        return '\n'.join(lines)

    def get_summary(self) -> str:
        """Print translation summary"""
        lines = []
        lines.append(f"Translation Summary:")
        lines.append(f"  ARM instructions parsed: {len(self.arm_instructions)}")
        lines.append(f"  RV64I instructions generated: {len(self.rv_instructions)}")
        lines.append(f"  Labels: {len(self.labels)}")
        lines.append(f"  Code size: {len(self.rv_instructions) * 4} bytes")
        lines.append(f"  Address range: 0x{self.base_addr:04X} - 0x{self.base_addr + len(self.rv_instructions) * 4:04X}")
        lines.append(f"\n  Label addresses:")
        for name, addr in sorted(self.labels.items(), key=lambda x: x[1]):
            lines.append(f"    {name:20s} = 0x{addr:04X} (word {addr // 4})")
        return '\n'.join(lines)


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description='ARM (ARMv4T) to RV64I Cross-Translator',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s sort.s -o sort
  %(prog)s sort.s --verilog --hex --asm
  %(prog)s sort.s --base-addr 0x200 -o thread1

Register Mapping (ARM -> RV64I):
  r0-r12  -> x10-x22
  sp(r13) -> x2
  lr(r14) -> x1
  fp(r11) -> x8
  ip(r12) -> x22
        """)
    parser.add_argument('input', help='Input ARM assembly file (.s)')
    parser.add_argument('-o', '--output', default=None,
                        help='Output file prefix (default: input name)')
    parser.add_argument('--base-addr', type=lambda x: int(x, 0), default=0,
                        help='Base address for generated code (default: 0)')
    parser.add_argument('--hex', action='store_true', help='Generate .hex file')
    parser.add_argument('--asm', action='store_true', help='Generate .S assembly file')
    parser.add_argument('--verilog', action='store_true', help='Generate Verilog init')
    parser.add_argument('--all', action='store_true', help='Generate all output formats')
    parser.add_argument('-v', '--verbose', action='store_true', help='Verbose output')

    args = parser.parse_args()

    if args.all:
        args.hex = args.asm = args.verilog = True

    # Default: generate everything
    if not (args.hex or args.asm or args.verilog):
        args.hex = args.asm = args.verilog = True

    output_prefix = args.output or args.input.rsplit('.', 1)[0]

    # Read input
    with open(args.input, 'r') as f:
        lines = f.readlines()

    # Translate
    translator = ARM2RV64Translator(base_addr=args.base_addr)
    translator.parse(lines)
    translator.translate()

    # Print summary
    print(translator.get_summary())

    # Generate outputs
    if args.asm:
        outfile = f"{output_prefix}_rv64i.S"
        with open(outfile, 'w') as f:
            f.write(f"# Auto-generated RV64I assembly from {args.input}\n")
            f.write(f"# Base address: 0x{args.base_addr:04X}\n\n")
            f.write(translator.get_asm())
        print(f"\n  RV64I assembly written to: {outfile}")

    if args.hex:
        outfile = f"{output_prefix}_rv64i.hex"
        with open(outfile, 'w') as f:
            f.write(translator.get_hex())
        print(f"  Hex file written to: {outfile}")

    if args.verilog:
        outfile = f"{output_prefix}_rv64i.v"
        with open(outfile, 'w') as f:
            f.write(f"// Auto-generated Verilog init from {args.input}\n")
            f.write(f"// Base address: 0x{args.base_addr:04X}\n\n")
            f.write(translator.get_verilog())
        print(f"  Verilog init written to: {outfile}")

    if args.verbose:
        print(f"\n{'=' * 60}")
        print("Generated RV64I Assembly:")
        print('=' * 60)
        print(translator.get_asm())


if __name__ == '__main__':
    main()